/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Supervisor;

/**
 *
 * @author shiba
 */
public class SUpervisorProcessReq extends javax.swing.JPanel {

    /**
     * Creates new form SUpervisorProcessReq
     */
    public SUpervisorProcessReq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        assignNetworkCombo = new javax.swing.JComboBox();
        commentsJTextField = new javax.swing.JTextField();
        resultComboBox = new javax.swing.JComboBox();
        submitJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        jLabel7.setText("Process Work Request:");

        jLabel1.setText("Request Result");

        jLabel2.setText("Add comments: ");

        jLabel3.setText("Assign Location");

        assignNetworkCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        assignNetworkCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignNetworkComboActionPerformed(evt);
            }
        });

        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        submitJButton.setText("Submit ");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(120, 120, 120))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(assignNetworkCombo, 0, 163, Short.MAX_VALUE)
                                    .addComponent(commentsJTextField)
                                    .addComponent(resultComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(submitJButton)))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(commentsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(assignNetworkCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(submitJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignNetworkComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignNetworkComboActionPerformed

    }//GEN-LAST:event_assignNetworkComboActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
//////        if(resultComboBox.getSelectedIndex()<0 || commentsJTextField.getText().trim().isEmpty() ||
//////            assignNetworkCombo.getSelectedIndex()<1)
//////        {
//////            JOptionPane.showMessageDialog(null, "Please enter data in all fields", "warning", JOptionPane.WARNING_MESSAGE);
//////            return;
//////        }
//////        Network net = (Network)assignNetworkCombo.getSelectedItem();
//////
//////        if((request.getSender().getRole().toString()).equalsIgnoreCase("VolunteerRole"))
//////        {
//////            Volunteer volunteer = (Volunteer)request.getSender().getPerson();
//////
//////            String[] longlat = LatLong.getLatLongForVolunteer(net.getCity());
//////            volunteer.setLongitude(longlat[0]);
//////            volunteer.setLatitiude(longlat[1]);
//////        }
//////
//////        request.setStatus(SupervisorWorkRequest.REQUEST_COMPLETED);
//////        request.setResolveDate(new Date());
//////        request.setTestResult((String)resultComboBox.getSelectedItem());
//////        request.setComments(commentsJTextField.getText());
//////        request.getSender().setNetwork(net);
//////
//////        if(request.getTestResult().equals(SupervisorWorkRequest.REQUEST_APPROVED))
//////        {
//////            request.getSender().setEnabled(true);
//////
//////            String emailId = request.getSender().getPerson().getEmailId();
//////            String userName = request.getSender().getUserName();
//////            String password = request.getSender().getPassword();
//////
//////            StringBuilder emailMsgTxt = new StringBuilder();
//////            emailMsgTxt.append("Your account is enabled. Please find username and password");
//////            emailMsgTxt.append(System.lineSeparator());
//////            emailMsgTxt.append("username : ".concat(userName));
//////            emailMsgTxt.append(System.lineSeparator());
//////            emailMsgTxt.append("password : ".concat(password));
//////            emailMsgTxt.append(System.lineSeparator());
//////            emailMsgTxt.append(System.lineSeparator());
//////            emailMsgTxt.append("Thank You");
//////            emailMsgTxt.append("HeartHelp");
//////
//////            boolean emailSent = SendEmailAndTextMessage.sendEmail(emailMsgTxt.toString(),emailId,userName, password);
//////            if(!emailSent)
//////            {
//////                JOptionPane.showMessageDialog(null, "Unable to send email,Please Try again! ","warning", JOptionPane.WARNING_MESSAGE);
//////                return;
//////            }
//////        }
//////        JOptionPane.showMessageDialog(null, "Request has been processed successfully", "success", JOptionPane.PLAIN_MESSAGE);
//////        commentsJTextField.setText("");
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
//
//        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
//        SupervisorWorkAreaJPanel supervisorWorkAreaJPanel = (SupervisorWorkAreaJPanel) component;
//        supervisorWorkAreaJPanel.populateWorkRequestTable();
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox assignNetworkCombo;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField commentsJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
